contact_links:
  - name: Focus Area Proposal
    url: https://github.com/web-platform-tests/interop/blob/main/2023/README.md#making-a-proposal
    about: The call for proposals for 2023 is now closed; check back next year for 2024.
  - name: Investigation Effort Proposal
    url: https://github.com/web-platform-tests/interop/blob/main/2023/README.md#making-a-proposal
    about: The call for proposals for 2023 is now closed; check back next year for 2024.
